### ISSUE TITLE
Building failing after updating autoprefixer to 10.3.3

### ISSUE THREAD

**Issue by owensgit** [Legal-and-General/canopy#542]
> The build for this is failing (as was the PR for the previous patch version). Running the build locally and checking the angular-logs it seems there is something in `sync-rpc` (a dependency of `ng-packagr` which is causing issues for this package. One option could be to close this PR and wait to see if updates in `ng-packagr` become more compatible or if future changes in autoprefixer become compatible with `sync-rpc` whilst also raising an issue on the autoprefixer package. At present these patches only provide support for `::file-selector-button` which I'm not sure is being used.

_Originally posted by @aaronBery in https://github.com/Legal-and-General/canopy/issues/539#issuecomment-910130127_

As agreed in the Dependabot PR above, we closed it and create this issue for future investigation.

**Comment by aaronBery** [comment]
Looking at the angular-logs it appears the error comes from the stylesheetProcessor in `ng-packagr` which must be running on the output of the autoprefixer. It is either correctly flagging the android version 91 as unknown or needs updating itself to accept this value. Will need further investigation before opening an issue on either package's repo

```
[error] Error: Unknown version 91 of android
    at extractValue (/Users/joebloggs/Projects/canopy/node_modules/sync-rpc/lib/index.js:165:19)
    at StylesheetProcessor.styleSheetProcessorWorker (/Users/joebloggs/Projects/canopy/node_modules/sync-rpc/lib/index.js:175:12)
    at StylesheetProcessor.process (/Users/joebloggs/Projects/canopy/node_modules/ng-packagr/lib/styles/stylesheet-processor.js:30:40)
    at Object.readResource (/Users/joebloggs/Projects/canopy/node_modules/ng-packagr/lib/ts/cache-compiler-host.js:91:57)
    at TsCompilerAotCompilerTypeCheckHostAdapter.loadResource (/Users/joebloggs/Projects/canopy/node_modules/@angular/compiler-cli/src/transformers/compiler_host.js:504:37)
    at Object.get (/Users/joebloggs/Projects/canopy/node_modules/@angular/compiler/bundles/compiler.umd.js:29957:94)
    at DirectiveNormalizer._fetch (/Users/joebloggs/Projects/canopy/node_modules/@angular/compiler/bundles/compiler.umd.js:21799:47)
    at /Users/joebloggs/Projects/canopy/node_modules/@angular/compiler/bundles/compiler.umd.js:21929:72
    at Array.map (<anonymous>)
    at DirectiveNormalizer._loadMissingExternalStylesheets (/Users/joebloggs/Projects/canopy/node_modules/@angular/compiler/bundles/compiler.umd.js:21929:18)
```
